   services:
     - type: web
       name: live-greeting
       env: elixir
       buildCommand: mix deps.get && mix compile
       startCommand: mix phx.server
       envVars:
         - key: SECRET_KEY_BASE
           generateValue: true
         - key: PHX_HOST
           value: live-greeting.onrender.com
         - key: PORT
           value: 10000