import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :live_greeting, LiveGreetingWeb.Endpoint,
  url: [host: "live-greeting.onrender.com", port: 443, scheme: "https"],
  http: [port: String.to_integer(System.get_env("PORT") || "4000")],
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: false,
  code_reloader: false,
  root: ".",
  version: Application.spec(:phoenix, :vsn),
  server: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: LiveGreeting.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
